### ISSUE TITLE
薬瓶に薬名の吹き出しをつける

### ISSUE THREAD

**Issue by hotaru3** [nkc-ryuji-togaru/VR-Project#34]
薬瓶に薬名の吹き出しをつける

薬瓶に薬名の吹き出しを表示させるようにする。
吹き出しはプレイヤーが薬瓶を掴んでいる間だけ表示させるようにして、プレイヤーが薬瓶から手を離したら吹き出しが消えるようにする。

薬瓶の上部に吹き出し画像を表示して、その前面に薬名のテキストを表示させるという形にする。
汎用性を高めるため、薬名はテキストデータを読み込んで表示させるようにする。

なお、空瓶には吹き出しを表示しなくてよい。

※備考
チャットワークに画像付きの仕様書と暫定的に選定した吹き出しPNG画像を用意したので、そちらも確認していただければ幸いです。

**Comment by nkc-ryuji-togaru** [comment]
薬を作り鍋にビンを突っ込むと鍋の近くにポップアップを表示する仕組みで実装。
これで問題なければ吹き出しの代わりでどうでしょう？
